# Generated by Django 5.1.3 on 2024-11-14 17:35

import django.db.models.deletion
import django.db.models.fields.related
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressProof',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('Aadhar', 'Aadhar'), ('ElectricityBill', 'ElectricityBill'), ('WaterBill', 'WaterBill')], max_length=50)),
                ('document_number', models.CharField(blank=True, max_length=50)),
                ('document', models.FileField(upload_to='documents/address_proof/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('applicant', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('UnderMRO', 'UnderMRO'), ('UnderVRO', 'UnderVRO'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], max_length=50)),
                ('application_area', models.CharField(max_length=30)),
                ('application_applied', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('village', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('mandal', models.CharField(max_length=20, null=True)),
                ('pincode', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=30)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='application.application')),
            ],
        ),
        migrations.CreateModel(
            name='CasteProof',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('BloodRelationCaste', 'BloodRelationCaste')], max_length=50)),
                ('document', models.FileField(upload_to='documents/caste_proof/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='DOBProof',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('PAN', 'PAN'), ('SSC', 'SSC'), ('TC', 'TransferCertificate')], max_length=50)),
                ('document_number', models.CharField(blank=True, max_length=50)),
                ('document', models.FileField(upload_to='documents/dob_proof/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customuser')),
            ],
        ),
    ]
